version: "3.9"


services:

  # Infrastructure
  # start separately for now
  
  # Provider
  provider-control-plane:
    extends:
      file: docker-compose-edc.yaml
      service: control-plane
    ports:
      - "9193:9193" # data management api - should be private later on
    volumes:
      - ${PROVIDER_CONTROL_PLANE_CONFIGURATION_PROPERTIES_FILE:-./configs/provider/control-plane.properties}:/app/configuration.properties
    environment:
          - EDC_RECEIVER_HTTP_DYNAMIC_ENDPOINT=${PROVIDER_EDC_RECEIVER_HTTP_ENDPOINT:-http://provider-receiver-service:8000/datareference}

  provider-data-plane:
    extends:
      file: docker-compose-edc.yaml
      service: data-plane
    volumes:
      - ${PROVIDER_DATA_PLANE_CONFIGURATION_PROPERTIES_FILE:-./configs/provider/data-plane.properties}:/app/configuration.properties

  # Consumer
  consumer-control-plane:
    extends:
      file: docker-compose-edc.yaml
      service: control-plane
    volumes:
      - ${CONSUMER_CONTROL_PLANE_CONFIGURATION_PROPERTIES_FILE:-./configs/consumer/control-plane.properties}:/app/configuration.properties
    environment:
      # renamed in 0.3.0
      - EDC_RECEIVER_HTTP_DYNAMIC_ENDPOINT=${EDC_RECEIVER_HTTP_ENDPOINT:-http://receiver-service:8000/datareference}

  consumer-data-plane:
    extends:
      file: docker-compose-edc.yaml
      service: data-plane
    volumes:
      - ${CONSUMER_DATA_PLANE_CONFIGURATION_PROPERTIES_FILE:-./configs/consumer/data-plane.properties}:/app/configuration.properties

  # Third
  third-control-plane:
    extends:
      file: docker-compose-edc.yaml
      service: control-plane
    volumes:
      - ${THIRD_CONTROL_PLANE_CONFIGURATION_PROPERTIES_FILE:-./configs/third/control-plane.properties}:/app/configuration.properties
    environment:
      # renamed in 0.3.0
      - EDC_RECEIVER_HTTP_DYNAMIC_ENDPOINT=${THIRD_EDC_RECEIVER_HTTP_ENDPOINT:-http://third-receiver-service:8000/datareference}
  third-data-plane:
    extends:
      file: docker-compose-edc.yaml
      service: data-plane
    volumes:
      - ${THIRD_DATA_PLANE_CONFIGURATION_PROPERTIES_FILE:-./configs/third/data-plane.properties}:/app/configuration.properties
