version: "3.9"

services:
  cx-services-mocks:
    build: ./docker/cx-services-mocks
    ports:
      - "127.0.0.1:8006:8080"

  callback-service:
    build: ./docker/callback-service

  pycxids:
    # dummy container with installed pycxids
    build: ./docker/pycxids
