version: "3.9"

services:
  receiver-service:
    # token_receiver_service for 'consumer' EDC instance
    build: ./docker/receiver-service
    ports:
      - "127.0.0.1:8003:8000"

  third-receiver-service:
    # token_receiver_service for 'third' EDC instance
    build: ./docker/receiver-service
    environment:
      - CONSUMER_EDC_BASE_URL=http://third-control-plane:9193/api/v1/data
      - CONSUMER_EDC_VALIDATION_ENDPOINT=http://third-control-plane:9192/validation/token

  dummy-backend:
    build: ./docker/dummy-backend
    ports:
      - "127.0.0.1:8002:8000"

  daps-token-service:
    build: ./docker/daps-token-service
    ports:
      - "127.0.0.1:8004:8000"
    environment:
      - BASIC_AUTH_PASSWORD=${DAPS_TOKEN_SERVICE_BASIC_AUTH_PASSWORD:-dontuseinpublic}
      - PRIVATE_KEY_FN=/private.key
      - CLIENT_ID=${DAPS_TOKEN_SERVICE_CLIENT_ID:-consumer} # used also in EDC settings
    volumes:
      - ${DAPS_TOKEN_SERVICE_PRIVATE_KEY_FN:-./vault_secrets/consumer.key}:/private.key

  pycxids:
    # dummy container with installed pycxids
    build: ./docker/pycxids
