edc.ids.id=urn:connector:provider-control-plane
ids.webhook.address=http://provider-control-plane:8282
edc.dsp.callback.address=http://provider-control-plane:8282

edc.participant.id=BPNLprovider


tx.ssi.endpoint.audience=http://provider-control-plane:8282

# IATP 0.7.0 changes
# https://github.com/eclipse-tractusx/tractusx-edc/blob/eb2bbf5ab2829ab7398752583ebf5007b9d1725a/edc-tests/edc-controlplane/fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/participant/TractusxParticipantBase.java#L116
# iatp.* -> edc.iam.*
edc.iam.issuer.id=did:web:dev%3A13000:BPNLprovider
edc.iam.trusted-issuer.issuer1.id=did:web:dev%3A13000:BPNLissuer
edc.iam.sts.oauth.token.url=http://dev:13000/dummy/token
edc.iam.sts.oauth.client.id=BPNLprovider
edc.iam.sts.oauth.client.secret.alias=provider.ssi.secret
edc.iam.sts.dim.url=http://dev:13000/sts
tx.iam.iatp.bdrs.server.url=http://dev:13000/bdrs
#tx.iam.iatp.bdrs.server.url=http://cx-services-mocks:8080/bdrs
# required to fetch the DID document from the mocked non-SSL endpoint
edc.iam.did.web.use.https=false

web.http.port=9191
web.http.path=/api

web.http.validation.port=9192
web.http.validation.path=/validation

web.http.catalog.port=8085
web.http.catalog.path=/catalog

web.http.control.port=8083
web.http.control.path=/control

edc.api.auth.key=dontuseinpublic

# new in 0.3.0 - only 1 setting can be enabled
web.http.management.port=9193
web.http.management.path=/api/v1/data
# until 0.1.6
#web.http.data.port=9193
#web.http.data.path=/api/v1/data


# 0.9.0 changed from 'ids' in 'protocol'
web.http.protocol.port=8282
# 0.9.0 because of any reason, the default /api/v1/dsp does not work anymore and returns method errors (POST vs GET)
web.http.protocol.path=/

# This is now set via docker compose ENV var!
# Please make sure to set as an environment variable!
# Reason: Easier to configure different endpoints via .env file
#edc.receiver.http.endpoint=http://provider-control-plane:8181/api/service/pull

edc.transfer.proxy.token.signer.privatekey.alias=provider.key
edc.transfer.proxy.token.verifier.publickey.alias=provider.crt

### Vault ###
edc.vault.hashicorp.url=http://vault:8200
edc.vault.hashicorp.token=dontuseinpublic
#edc.vault.hashicorp.api.secret.path=/v1/secret
#edc.vault.hashicorp.api.secret.path=/v1/secret
#edc.vault.hashicorp.health.check.standby.ok=true
#disable annoying logging - do we need this enabled?
edc.vault.hashicorp.health.check.enabled=false

edc.security.private-key.alias=provider.key
edc.public.key.alias=provider.crt


edc.oauth.public.key.alias=provider.crt
edc.oauth.private.key.alias=provider.key

edc.data.encryption.keys.alias=provider-encryption.keys

# starting from 0.4.0 with new protocol
edc.oauth.endpoint.audience=http://provider-control-plane:8282/api/v1/dsp

# postgres db config
edc.datasource.default.url=jdbc:postgresql://db/edc_provider
edc.datasource.default.user=postgres
edc.datasource.default.password=admin
