web.http.port=9191
web.http.path=/api
web.http.public.port=9192
web.http.public.path=/public

# IATP 0.7.0 changes
# https://github.com/eclipse-tractusx/tractusx-edc/blob/eb2bbf5ab2829ab7398752583ebf5007b9d1725a/edc-tests/edc-controlplane/fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/participant/TractusxParticipantBase.java#L116
# iatp.* -> edc.iam.*
edc.iam.issuer.id=did:web:dev%3A13000:BPNLprovider
edc.iam.trusted-issuer.issuer1.id=did:web:dev%3A13000:BPNLissuer
edc.iam.sts.oauth.token.url=http://dev:13000/dummy/token
edc.iam.sts.oauth.client.id=BPNLprovider
edc.iam.sts.oauth.client.secret.alias=provider.ssi.secret
edc.iam.sts.dim.url=http://dev:13000/sts
tx.iam.iatp.bdrs.server.url=http://dev:13000/bdrs
#tx.iam.iatp.bdrs.server.url=http://cx-services-mocks:8080/bdrs
# required to fetch the DID document from the mocked non-SSL endpoint
edc.iam.did.web.use.https=false


# new in 0.3.3 - why do we need the management in a data plane?
web.http.management.port=9194
web.http.management.path=/api/v1/data

# Not sure if the following two are needed
web.http.control.port=9193
web.http.control.path=/control

edc.dataplane.token.validation.endpoint=http://provider-control-plane:9191/api/token
### Vault ###
edc.vault.hashicorp.url=http://vault:8200
edc.vault.hashicorp.token=dontuseinpublic
#disable annoying logging - do we need this enabled?
edc.vault.hashicorp.health.check.enabled=false

# AWS config
#edc.aws.endpoint.override=http://dev:5000
edc.aws.access.key=matthias-test-user-provider_access_key
edc.aws.secret.access.key=matthias-test-user-provider_secret_access_key

# new in 0.7.0
edc.dataplane.api.public.baseurl=http://provider-data-plane:9192/public

web.http.signaling.port=8283
web.http.signaling.path=/api/signaling

edc.transfer.proxy.token.signer.privatekey.alias=provider.key
edc.transfer.proxy.token.verifier.publickey.alias=provider.crt

edc.datasource.default.url=jdbc:postgresql://db/edc_provider
edc.datasource.default.user=postgres
edc.datasource.default.password=admin

# new in 0.8.0
edc.dpf.selector.url=http://provider-control-plane:8083/control/v1/dataplanes
edc.control.endpoint=http://provider-data-plane:9193/control
